---
development:
  cloud_name: dnffmpcmo
  api_key: '695111358838231'
  api_secret: 83Aax3boJi338NhE7RJrqnhrBDc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dnffmpcmo
  api_key: '695111358838231'
  api_secret: 83Aax3boJi338NhE7RJrqnhrBDc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dnffmpcmo
  api_key: '695111358838231'
  api_secret: 83Aax3boJi338NhE7RJrqnhrBDc
  enhance_image_tag: true
  static_image_support: false
